# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d7638dac3a2eabbf0e92643ab2b62c7f0a28cdb13eee6606dcc8349cf8a1fef5d61a3b23aca31c404922f518e38f9c3dc720f7ef34c8ef32039a9c0e787002

test:
  secret_key_base: 0af99d0175a073d28378f3a9ad0c7828bbc1c3633f8826c8e515ed442de4f526aa27e85297ca0d8d83ccc021841fa09b29647c4ff885fa032c7737cca13c52bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
